export const PRESS_DIGIT = 'PRESS_DIGIT';
export const PRESS_OPERATOR = 'PRESS_OPERATOR';
export const EQUALS = 'EQUALS';
export const CLEAR_CALCULATOR = 'CLEAR_CALCULATOR';
export const DECIMAL_POINT = 'DECIMAL_POINT';
export const UPDATE_MOUSE_POSITION = 'UPDATE_MOUSE_POSITION';
